version: '3.8'

services:
  api:
    build: .
    container_name: express_api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/devboard
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - devnet

  mongo:
    image: mongo:6.0
    container_name: express_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - devnet

volumes:
  mongo-data:

networks:
  devnet:
    driver: bridge
